export const props = [
    { 
        player: "S1MPLE",
        team: "CS2 (NAVI)", 
        match: "NAVI vs FAZE", 
        matchDate: 'Tue, Dec 12th : 9:00pm', 
        stats: 'Map 1 - 2 kills', 
        ou: "Over",
        p: "24.5", 
        odds: "-214", 
        vs: "74%",
        l5: "74%",
        l10: "74%",
        l30: "74%",
    },
    { 
        player: "S1MPLE",
        team: "CS2 (NAVI)", 
        match: "NAVI vs FAZE", 
        matchDate: 'Tue, Dec 12th : 9:00pm', 
        stats: 'Map 1 - 2 kills', 
        ou: "Over",
        p: "24.5", 
        odds: "-214", 
        vs: "74%",
        l5: "74%",
        l10: "74%",
        l30: "74%",
    },
    { 
        player: "S1MPLE",
        team: "CS2 (NAVI)", 
        match: "NAVI vs FAZE", 
        matchDate: 'Tue, Dec 12th : 9:00pm', 
        stats: 'Map 1 - 2 kills', 
        ou: "Over",
        p: "24.5", 
        odds: "-214", 
        vs: "74%",
        l5: "74%",
        l10: "74%",
        l30: "74%",
    },
    { 
        player: "S1MPLE",
        team: "CS2 (NAVI)", 
        match: "NAVI vs FAZE", 
        matchDate: 'Tue, Dec 12th : 9:00pm', 
        stats: 'Map 1 - 2 kills', 
        ou: "Over",
        p: "24.5", 
        odds: "-214", 
        vs: "74%",
        l5: "74%",
        l10: "74%",
        l30: "74%",
    },
    { 
        player: "S1MPLE",
        team: "CS2 (NAVI)", 
        match: "NAVI vs FAZE", 
        matchDate: 'Tue, Dec 12th : 9:00pm', 
        stats: 'Map 1 - 2 kills', 
        ou: "Over",
        p: "24.5", 
        odds: "-214", 
        vs: "74%",
        l5: "74%",
        l10: "74%",
        l30: "74%",
    },
    { 
        player: "S1MPLE",
        team: "CS2 (NAVI)", 
        match: "NAVI vs FAZE", 
        matchDate: 'Tue, Dec 12th : 9:00pm', 
        stats: 'Map 1 - 2 kills', 
        ou: "Over",
        p: "24.5", 
        odds: "-214", 
        vs: "74%",
        l5: "74%",
        l10: "74%",
        l30: "74%",
    },
    { 
        player: "S1MPLE",
        team: "CS2 (NAVI)", 
        match: "NAVI vs FAZE", 
        matchDate: 'Tue, Dec 12th : 9:00pm', 
        stats: 'Map 1 - 2 kills', 
        ou: "Over",
        p: "24.5", 
        odds: "-214", 
        vs: "74%",
        l5: "74%",
        l10: "74%",
        l30: "74%",
    },
    { 
        player: "S1MPLE",
        team: "CS2 (NAVI)", 
        match: "NAVI vs FAZE", 
        matchDate: 'Tue, Dec 12th : 9:00pm', 
        stats: 'Map 1 - 2 kills', 
        ou: "Over",
        p: "24.5", 
        odds: "-214", 
        vs: "74%",
        l5: "74%",
        l10: "74%",
        l30: "74%",
    },
];