export const tools = [
    { 
        player: "S1MPLE",
        team: "CS2 (NAVI)", 
        match: "NAVI vs FAZE", 
        matchDate: 'Tue, Dec 12th : 9:00pm', 
        stats: 'Map 1 - 2 kills', 
        ou: "Over",
        p: "24.5", 
        odds: "14", 
        se: "24.5",
        i1: ["7", "64"],
        i2: ["7", "64"],
    },
    { 
        player: "S1MPLE",
        team: "CS2 (NAVI)", 
        match: "NAVI vs FAZE", 
        matchDate: 'Tue, Dec 12th : 9:00pm', 
        stats: 'Map 1 - 2 kills', 
        ou: "Over",
        p: "24.5", 
        odds: "14", 
        se: "24.5",
        i1: ["7", "64"],
        i2: ["7", "64"],
    },
    { 
        player: "S1MPLE",
        team: "CS2 (NAVI)", 
        match: "NAVI vs FAZE", 
        matchDate: 'Tue, Dec 12th : 9:00pm', 
        stats: 'Map 1 - 2 kills', 
        ou: "Over",
        p: "24.5", 
        odds: "14", 
        se: "24.5",
        i1: ["7", "64"],
        i2: ["7", "64"],
    },
    { 
        player: "S1MPLE",
        team: "CS2 (NAVI)", 
        match: "NAVI vs FAZE", 
        matchDate: 'Tue, Dec 12th : 9:00pm', 
        stats: 'Map 1 - 2 kills', 
        ou: "Over",
        p: "24.5", 
        odds: "14", 
        se: "24.5",
        i1: ["7", "64"],
        i2: ["7", "64"],
    },
    { 
        player: "S1MPLE",
        team: "CS2 (NAVI)", 
        match: "NAVI vs FAZE", 
        matchDate: 'Tue, Dec 12th : 9:00pm', 
        stats: 'Map 1 - 2 kills', 
        ou: "Over",
        p: "24.5", 
        odds: "14", 
        se: "24.5",
        i1: ["7", "64"],
        i2: ["7", "64"],
    },
    { 
        player: "S1MPLE",
        team: "CS2 (NAVI)", 
        match: "NAVI vs FAZE", 
        matchDate: 'Tue, Dec 12th : 9:00pm', 
        stats: 'Map 1 - 2 kills', 
        ou: "Over",
        p: "24.5", 
        odds: "14", 
        se: "24.5",
        i1: ["7", "64"],
        i2: ["7", "64"],
    },
];